### ISSUE TITLE
Add Simple Login Page to Flashcards

### ISSUE THREAD

**Issue by user-64bit** [arth2002/Flashcards#2]
we want to Include Login System in it. so we can make it more secure.
Login Page doesn't need to be too fancy. (if you want you can make it thoughh)

Just add the Simple Login page which takes *username* and *password* from some *.txt* file or *.env* file.
Feel free ask more about the issue.
Thanks :smile:

**Comment by renzocabarios** [comment]
Can I be assigned to do this issue?

**Comment by user-64bit** [comment]
Sure. Thanks for your help

Don't forget to star :star:  this Repo.
Thanks

**Comment by user-64bit** [comment]
Hey, @renzocabarios 
You haven't forked this repo yet.
Are you still working on this?
Please give some response.

**Comment by renzocabarios** [comment]
Sorry i got busy. You can give it to someone else

**Comment by MaruthiKo** [comment]
Hey can I would like to work on this issue, but I'm new to contributing in open source, but willing to work on anything with a little guidance

**Comment by user-64bit** [comment]
Sure, You can @MaruthiKo 
Thanks for your contributions. :smile: 

Happy Coding
(Don't forget to star :star:  this Repo)

**Comment by MaruthiKo** [comment]
So to be clear about the issue, you want me to create a login page using HTML and CSS

**Comment by user-64bit** [comment]
@MaruthiKo 
Yes You have to design a Login page using HTML and CSS (you can use bootstrap etc too)
And You have to use Python(Django) to verify details.
Tell me if you want more details.
Thanks

**Comment by MaruthiKo** [comment]
Alright, will work the HTML & CSS part first, but I have never used Django will find an alternative using JS
Not a problem
Will try to make it as soon as possible
Thanks for the info

**Comment by user-64bit** [comment]
Sure
And If there is mandatory Django code then I'll guide you
Don't worry :smile:

**Comment by MaruthiKo** [comment]
Hey, Completed with the UI
<img width="959" alt="Screenshot (9)" src="https://user-images.githubusercontent.com/63769209/194857634-02cd1078-e7f6-4233-935d-6bcca6bacf20.png">

**Comment by user-64bit** [comment]
Hey @MaruthiKo 
It looks pretty cool :cool: 
How's the backend part going?
Tell me if you need any help :smile:

**Comment by MaruthiKo** [comment]
Working on it, not having any problem until now, but can you give me a quick overview of what you are looking in the backend so, I can make sure I'm on the right track

**Comment by user-64bit** [comment]
I don't want any complex login system right now.
I just want this login system to take input from the `.txt` file(`username`, `password`) and verify it.
(Ex: `creadentials.txt` has `username`=`arth` and `password`=`password`, so when the user input this credentials then the user will be logged in)
Simple, Isn't it?

**Comment by MaruthiKo** [comment]
Yes simple and you explained it very well. Thank you
Will try to work on it and let u know if I have any doubt

**Comment by MaruthiKo** [comment]
Hey, I have done what I could, now I have opened pull request. Let me know if anything has to be changed
