### ISSUE TITLE
Add Register Page to Flashcards

### ISSUE THREAD

**Issue by user-64bit** [arth2002/Flashcards#3]
Here, We want a simple Register Page which will have a simple UI (if you want you can make it fancy)
The registration Page will have Simple details like *name*, *username*, *password*, *Confirm password*.

Now we want to store this detail on some file *.txt* or *.env* file.

Because on the login page we're grabbing these details from the file.

Thanks :smiley: 
Feel free to ask for help :+1:

**Comment by samyaksand** [comment]
Hello, Im interested in working on this. Please assign me this issue.

**Comment by user-64bit** [comment]
Sure. You can work on this. :+1: 
Thanks for your help. :smile: 

Don't forget to star :star:  this repo.

**Comment by samyaksand** [comment]
Thank you!

**Comment by piyushkandari** [comment]
I am new to open source,please assign me this for further learning

**Comment by user-64bit** [comment]
Hey @samyaksand 
You haven't forked this repo yet...
Are you working on this?
Please Give some Response.

**Comment by samyaksand** [comment]
Hello, yes Im working on it. By tomorrow, I will send a pr

**Comment by user-64bit** [comment]
No Worries
You can take your time :smile:

**Comment by user-64bit** [comment]
Hey @samyaksand 
How's it going?

There is no hurry just be active here. :smiley: 
So I can make sure that you're still working on this issue. :smile: 
Happy Coding. :+1: 
Thanks:smiley:

**Comment by user-64bit** [comment]
Hey @samyaksand 
You didn't seem to be working on this issue.
I'll be unassigning you from this issue.

**Comment by nilesh05apr** [comment]
Hello @arth2002 i am working on this issue, i may not be able to add fancy UI but i will add the appropriate backend logic.

**Comment by user-64bit** [comment]
> Hello @arth2002 i am working on this issue, i may not be able to add fancy UI but i will add the appropriate backend logic.

Sounds cool.😁
If you want you can use UI of login page with some little changes.
Thanks for your contribution😄
Happy Coding 😊


[*Don't forget to Star ⭐ this Repo*]

**Comment by nilesh05apr** [comment]
@arth2002 i have opened a PR. Review it and add hacktoberfest label to it. Thanks
